---
# This Docker composition file is used to stand up an Apache Guacamole server
# with a PostgreSQL database backend and the guacscanner utility for
# auto-discovering and adding connections.

name: guacamole-composition

secrets:
  postgres_password:
    file: ./src/secrets/postgres-password
  postgres_username:
    file: ./src/secrets/postgres-username
  private_ssh_key:
    file: ./src/secrets/private-ssh-key
  rdp_password:
    file: ./src/secrets/rdp-password
  rdp_username:
    file: ./src/secrets/rdp-username
  vnc_password:
    file: ./src/secrets/vnc-password
  vnc_username:
    file: ./src/secrets/vnc-username
  windows_sftp_base:
    file: ./src/secrets/windows-sftp-base

volumes:
  dbdata:
  initdb:

services:
  guacd:
    container_name: guacd
    image: guacamole/guacd:1.6.0
    logging:
      driver: json-file
      options:
        max-size: 100m
    restart: always

  postgres:
    container_name: postgres
    environment:
      POSTGRES_DB: guacamole_db
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres-password
      POSTGRES_USER_FILE: /run/secrets/postgres-username
    healthcheck:
      interval: 10s
      retries: 5
      start_period: 30s
      test:
        - CMD-SHELL
        - pg_isready --dbname=$$POSTGRES_DB
      timeout: 5s
    image: postgres:18
    logging:
      driver: json-file
      options:
        max-size: 100m
    restart: always
    secrets:
      - source: postgres_password
        target: postgres-password
      - source: postgres_username
        target: postgres-username
    volumes:
      - read_only: true
        source: initdb
        target: /docker-entrypoint-initdb.d
        type: volume
      - source: dbdata
        target: /var/lib/postgresql
        type: volume

  guacamole:
    cap_add:
      # Required to allow listening on privileged port 80
      - NET_BIND_SERVICE
    command:
      - /bin/sh
      - -c
      - |
        export POSTGRESQL_USERNAME=$$(cat /run/secrets/postgres-username);
        export POSTGRESQL_PASSWORD=$$(cat /run/secrets/postgres-password);
        /opt/guacamole/bin/entrypoint.sh
    container_name: guacamole
    depends_on:
      guacd:
        condition: service_started
      postgres:
        condition: service_healthy
    environment:
      GUACD_HOSTNAME: guacd
      GUACD_PORT: 4822
      HTTP_AUTH_ENABLED: "true"
      POSTGRESQL_DATABASE: guacamole_db
      POSTGRESQL_ENABLED: "true"
      POSTGRESQL_HOSTNAME: postgres
      POSTGRESQL_PORT: 5432
    image: guacamole/guacamole:1.6.0
    logging:
      driver: json-file
      options:
        max-size: 100m
    ports:
      - 127.0.0.1:80:8080/tcp
    restart: always
    secrets:
      - source: postgres_password
        target: postgres-password
      - source: postgres_username
        target: postgres-username
    volumes:
      - read_only: true
        source: initdb
        target: /opt/guacamole/extensions/guacamole-auth-jdbc/postgresql/schema
        type: volume

  guacscanner:
    container_name: guacscanner
    depends_on:
      postgres:
        condition: service_healthy
    image: cisagov/guacscanner:1.2.1
    logging:
      driver: json-file
      options:
        max-size: 100m
    restart: always
    secrets:
      - source: postgres_password
        target: postgres-password
      - source: postgres_username
        target: postgres-username
      - source: private_ssh_key
        target: private-ssh-key
      - source: rdp_password
        target: rdp-password
      - source: rdp_username
        target: rdp-username
      - source: vnc_password
        target: vnc-password
      - source: vnc_username
        target: vnc-username
      - source: windows_sftp_base
        target: windows-sftp-base
