---
version: "3.1"

secrets:
  postgres_password:
    file: ./src/secrets/postgres-password
  postgres_username:
    file: ./src/secrets/postgres-username

volumes:
  dbdata:

services:
  init-guac-db:
    command:
      - /bin/sh
      - -c
      - |
        test -e /init/initdb.sql &&
        echo 'init file already exists' ||
        /opt/guacamole/bin/initdb.sh --postgres > /init/00_initdb.sql
    image: guacamole/guacamole
    volumes:
      - ./dbinit:/init

  guacd:
    container_name: guacd
    image: guacamole/guacd
    restart: always

  postgres:
    container_name: postgres
    depends_on:
      - init-guac-db
    environment:
      POSTGRES_DB: guacamole_db
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres-password
      POSTGRES_USER_FILE: /run/secrets/postgres-username
    image: postgres
    restart: always
    secrets:
      - source: postgres_password
        target: postgres-password
      - source: postgres_username
        target: postgres-username
    volumes:
      - ./dbinit:/docker-entrypoint-initdb.d:ro
      - dbdata:/var/lib/postgresql/data:rw

  guacamole:
    cap_add:
      # Required to allow listening on privileged port 80
      - NET_BIND_SERVICE
    command:
      - /bin/sh
      - -c
      - |
        export POSTGRES_USER=$$(cat /run/secrets/postgres-username);
        export POSTGRES_PASSWORD=$$(cat /run/secrets/postgres-password);
        /opt/guacamole/bin/start.sh
    container_name: guacamole
    depends_on:
      - guacd
      - postgres
    environment:
      GUACD_HOSTNAME: guacd
      GUACD_PORT: 4822
      HEADER_ENABLED: "true"
      POSTGRES_DATABASE: guacamole_db
      POSTGRES_HOSTNAME: postgres
      POSTGRES_PORT: 5432
    image: guacamole/guacamole
    ports:
      - "127.0.0.1:80:8080/tcp"
    restart: always
    secrets:
      - source: postgres_password
        target: postgres-password
      - source: postgres_username
        target: postgres-username
